name: CI
env:
  TARGET: ${{secrets.WEBSITE_URL}}
  TENABLE_ACCESS_KEY: ${{secrets.TENABLE_ACCESS_KEY}}
  TENABLE_SECRET_KEY: ${{secrets.TENABLE_SECRET_KEY}}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:


jobs:
  build:
    
    runs-on: ubuntu-latest

  
    steps:

      - uses: actions/checkout@v3

      - name: setup python 3.10.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9
      - name: setup python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4
          pip install urllib3
          pip install pytenable

          
      - name: Install OWASP ZAP
        run: |
          mkdir -p ./zap
          cd ./zap
          wget -N https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
          tar -zxvf ZAP_2.9.0_Linux.tar.gz
          rm ZAP_2.9.0_Linux.tar.gz
          cd ZAP_2.9.0/plugin
          wget https://github.com/zaproxy/zap-extensions/releases/download/exportreport-v6/exportreport-alpha-6.zap
          echo 'export PATH_ZAP_SH=./zap/ZAP_2.9.0/zap.sh' >> ~/.bashrc
          echo 'export ZAP_PORT=8090' >> ~/.bashrc
          echo 'sh -c "$PATH_ZAP_SH -daemon -host 0.0.0.0 -port $ZAP_PORT -configfile ./zap/ZAP_2.9.0/conf" > /dev/null & ' > start-zap
          echo 'sleep 40' >> start-zap
          echo 'sh -c "$PATH_ZAP_SH -host 0.0.0.0 -port $ZAP_PORT -configfile ./zap/ZAP_2.9.0/conf" > /dev/null & ' > start-gui-zap
          echo 'sleep 50' >> start-gui-zap
          echo 'pkill -f zap' > stop-zap
          chmod +x start-zap
          chmod +x start-gui-zap
          chmod +x stop-zap
          echo $pwd


      # - name: build broken crystals docker
      #   run : docker-compose --file=./brokencrystals-master/docker-compose.local.yml up -d 


      # - name: Wait for container to start
      #   run: sleep 10s  


      # - name: Run OWASP ZAP
      #   run: docker run -t owasp/zap2docker-stable zap-full-scan.py -t http://web

      - name: Run ZAP Daemon
        run: |
          ./zap/ZAP_2.9.0/zap.sh -daemon addoninstall soap -addoninstall openapi -host 0.0.0.0 -port 8091 -config api.addrs.addr.name=".*" -config api.addrs.addr.regex=true -config api.key= ${{secrets.TENABLE_ACCESS_KEY}} -config api.secret= ${{secrets.TENABLE_SECRET_KEY}} > /dev/null &
          
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Run Test Automation with ZAP
        run: |
          cd ./script/
          python zap.py
          python pytenable.py

      - name: "Upload Report"
        uses: actions/upload-artifact@v1
        with:
          name: zap-scan-report
          path: ./script/report.html 