name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:


jobs:
  build:
    
    runs-on: ubuntu-latest

  
    steps:

      - uses: actions/checkout@v3

      - name: setup python 3.10.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9
      - name: setup python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install webdriver_manager
          python -m pip install -U selenium
          
      - name: create docker network
        run: docker network create zapnet


      # - name:  pull zap/stable
      #   run: docker pull owasp/zap2docker-stable

      - name: build broken crystals docker
        run : docker-compose --file=./brokencrystals-master/docker-compose.local.yml up -d 


      - name: Wait for container to start
        run: sleep 10s  


      - name: Run OWASP ZAP
        run: docker run -t owasp/zap2docker-stable zap-full-scan.py -t http://web
      # - name: run ZAP full scan
      #   run:   docker run --user $(id -u):$(id -g) -v $(pwd):/zap/wrk/:rw --rm  --net zapnet  -t owasp/zap2docker-stable zap-baseline.py -t http://$(ip -f inet -o addr show eth0 | awk '{print $4}' | cut -d '/' -f 1):8090 -g gen.conf -r report.html 
     
      # - name: Stop Docker Compose environment
      #   run: |
         
      #     docker-compose down

      - name: upload report
        uses: actions/upload-artifact@v1
        with:
          name: zap-scan-report
          path: ./
